CREATE_TABLES_SCRIPT = """DROP TABLE IF EXISTS PATIENTS;
DROP TABLE IF EXISTS HOSPITAL_STAY;
DROP TABLE IF EXISTS DOCTORS;

CREATE TABLE PATIENTS
(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  FIRSTNAME VARCHAR(255) NOT NULL,
  LASTNAME VARCHAR(255) NOT NULL,
  AGE int NOT NULL,
  GENDER VARCHAR(6),
  DOCTOR INT,
  FOREIGN KEY(DOCTOR) REFERENCES DOCTORS(ID)
);

CREATE TABLE HOSPITAL_STAY
(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ROOM INT NOT NULL,
  STARTDATE DATE NOT NULL,
  ENDDATE DATE int,
  INJURY VARCHAR(255) NOT NULL,
  PATIENT INT,
  FOREIGN KEY(PATIENT) REFERENCES PATIENTS(ID)
);

CREATE TABLE DOCTORS
(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  FIRSTNAME VARCHAR(255) NOT NULL,
  LASTNAME VARCHAR(255) NOT NULL
);"""