# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
    ]
