# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170215_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='user_email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.User'),
        ),
    ]
