# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170215_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.User')),
            ],
        ),
    ]
