GET_ALL_MOVIES_ORDERED_BY_DATE = """
SELECT *
FROM movie
ORDER BY RATING DESC;"""







CREATE_TABLES = """DROP TABLE IF EXISTS MOVIE;
DROP TABLE IF EXISTS PROJECTIONS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS RESERVATIONS;


CREATE TABLE MOVIE (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME VARCHAR(100) NOT NULL,
	RATING REAL NOT NULL
);

CREATE TABLE PROJECTIONS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	MOVIE_ID INTEGER NOT NULL,
	TYPE VARCHAR(10) NOT NULL,
	PROJ_DATE VARCHAR(12) NOT NULL,
	TIME VARCHAR(5) NOT NULL,
	FOREIGN KEY(MOVIE_ID) REFERENCES MOVIE(ID)
);

CREATE TABLE USERS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	USERNAME VARCHAR(60) NOT NULL,
	PASSWORD VARCHAR(60) NOT NULL
);

CREATE TABLE RESERVATIONS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	USER_ID INTEGER NOT NULL,
	PROJECTION_ID INTEGER NOT NULL,
	ROW INTEGER NOT NULL,
	COL INTEGER NOT NULL,
	FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
	FOREIGN KEY(PROJECTION_ID) REFERENCES PROJECTIONS(ID)
);

INSERT INTO MOVIE (ID, NAME, RATING)
VALUES (1, "The Hunger Games: Catching Fire", 7.9);

INSERT INTO MOVIE (ID, NAME, RATING)
VALUES (2, "Wreck it-Ralph", 7.8);

INSERT INTO MOVIE (ID, NAME, RATING)
VALUES (3, "Her", 8.3);

INSERT INTO PROJECTIONS (ID, MOVIE_ID, TYPE, PROJ_DATE, TIME)
VALUES (1, 1, "3D", "2014-04-01", "19:10");

INSERT INTO PROJECTIONS (ID, MOVIE_ID, TYPE, PROJ_DATE, TIME)
VALUES (2, 1, "2D", "2014-04-01", "19:00");

INSERT INTO PROJECTIONS (ID, MOVIE_ID, TYPE, PROJ_DATE, TIME)
VALUES (3, 1, "4DX", "2014-04-02", "21:00");

INSERT INTO PROJECTIONS (ID, MOVIE_ID, TYPE, PROJ_DATE, TIME)
VALUES (4, 3, "2D", "2014-04-05", "20:20");

INSERT INTO PROJECTIONS (ID, MOVIE_ID, TYPE, PROJ_DATE, TIME)
VALUES (5, 2, "3D", "2014-04-02", "22:00");

INSERT INTO PROJECTIONS (ID, MOVIE_ID, TYPE, PROJ_DATE, TIME)
VALUES (6, 2, "2D", "2014-04-02", "19:30");

INSERT INTO USERS (ID, USERNAME, PASSWORD)
VALUES (1, "Rositsa Zlateva", "rosata");

INSERT INTO USERS (ID, USERNAME, PASSWORD)
VALUES (2, "Slavyana Monkova", "slavyana");

INSERT INTO USERS (ID, USERNAME, PASSWORD)
VALUES (3, "Radoslav Georgiev", "radoslav");

INSERT INTO USERS (ID, USERNAME, PASSWORD)
VALUES (4, "Krasimira Badova", "krasi");

INSERT INTO USERS (ID, USERNAME, PASSWORD)
VALUES (5, "Kiril Hristov", "kiril");

INSERT INTO USERS (ID, USERNAME, PASSWORD)
VALUES (6, "Vladimir Delchev", "vlado");


INSERT INTO RESERVATIONS (ID, USER_ID, PROJECTION_ID, ROW, COL)
VALUES (1, 3, 1, 2, 1);

INSERT INTO RESERVATIONS (ID, USER_ID, PROJECTION_ID, ROW, COL)
VALUES (2, 3, 1, 3, 5);

INSERT INTO RESERVATIONS (ID, USER_ID, PROJECTION_ID, ROW, COL)
VALUES (3, 3, 1, 7, 8);

INSERT INTO RESERVATIONS (ID, USER_ID, PROJECTION_ID, ROW, COL)
VALUES (4, 2, 3, 1, 1);

INSERT INTO RESERVATIONS (ID, USER_ID, PROJECTION_ID, ROW, COL)
VALUES (5, 2, 3, 1, 2);

INSERT INTO RESERVATIONS (ID, USER_ID, PROJECTION_ID, ROW, COL)
VALUES (6, 5, 5, 2, 3);

INSERT INTO RESERVATIONS (ID, USER_ID, PROJECTION_ID, ROW, COL)
VALUES (7, 6, 5, 2, 4);
"""